#!/usr/bin/env python3
"""Generate the Claude Code agent set from the Stella agent set.

The body of every agent is identical across both runtimes — only the
frontmatter differs. Stella reads `name`, `description`, `tools` and ignores
every other key; Claude Code additionally understands `model`. Tool names
differ entirely between the two runtimes, so they are mapped here.

Run from the repository root:

    python3 scripts/build-cc-agents.py

Source: agents/*.md          (Stella, canonical)
Output: agents/cc-agents/*.md (Claude Code, generated)

`agents/cc-agents/` deliberately contains no AGENT.md, so Stella's loader
skips the directory instead of loading a second, mis-tooled copy of every
agent.
"""
from __future__ import annotations

import os
import re
import sys

SRC = "agents"
OUT = os.path.join("agents", "cc-agents")

# Stella tool name -> Claude Code tool name(s).
TOOL_MAP: dict[str, list[str]] = {
    "read_file": ["Read"],
    "write_file": ["Write"],
    "edit_file": ["Edit"],
    "bash": ["Bash"],
    "search": ["Grep", "Glob"],
    "delegate": ["Task"],
    "task_create": ["TodoWrite"],
    "task_list": ["TodoWrite"],
    "task_start": ["TodoWrite"],
    "task_complete": ["TodoWrite"],
}

# Claude Code selects agents automatically from the description, so each one
# gets an explicit trigger clause that the terser Stella description omits.
# Stella caps descriptions at 80 characters; Claude Code has no such limit.
TRIGGERS: dict[str, str] = {
    "architect": "Use when planning a new feature, evaluating a design, or recording an architectural decision.",
    "code-reviewer": "Use on every pull request, and proactively after any agent-authored change lands.",
    "comment-auditor": "Use when comments are suspected of drifting from the code, or before a documentation pass.",
    "connector-author": "Use when adding a data source, integration, or ingestion plugin to a platform.",
    "database-reviewer": "Use proactively when writing queries, creating migrations, or designing schemas.",
    "debugger": "Use for any defect, flaky behavior, or environment-specific failure.",
    "demo-director": "Use for sales demos, launch videos, conference talks, and internal show-and-tells.",
    "docs-writer": "Use when features ship, when a parity audit finds undocumented capability, or when support questions repeat.",
    "e2e-tester": "Use proactively when critical user flows change or end-to-end tests start failing.",
    "feature-shipper": "Use to build a feature end to end, ideally with a surfacing spec from ux-architect.",
    "harness-optimizer": "Use when agent or command definitions need auditing, deduplicating, or repairing.",
    "launch-marketer": "Use at feature launch, at release milestones, or when positioning needs sharpening.",
    "output-evaluator": "Use after a non-trivial task when a quality assessment of the result is wanted.",
    "parity-auditor": "Use on a schedule or whenever new backend surface lands.",
    "perf-auditor": "Use when investigating slow paths, latency regressions, or resource growth.",
    "security-reviewer": "Use proactively after writing code that handles user input, authentication, or sensitive data.",
    "seo-specialist": "Use for site audits, metadata reviews, structured-data problems, and SEO remediation plans.",
    "silent-failure-hunter": "Use when failures are suspected of going unreported, or before hardening a service.",
    "simplifier": "Use proactively after feature merges, before refactors, or when review friction climbs.",
    "spec-builder": "Use when onboarding an existing codebase to spec-driven development.",
    "spec-design": "Use after the spec requirements document is approved.",
    "spec-judge": "Use to evaluate competing versions of a requirements, design, or tasks document.",
    "spec-requirements": "Use to start a spec workflow, before any design work.",
    "spec-tasks": "Use after the spec design document is approved.",
    "test-engineer": "Use when coverage is uncertain, before big refactors, when flakes appear, or when CI slows.",
    "typescript-reviewer": "Use for all TypeScript and JavaScript changes.",
    "usability-reviewer": "Use on every user-facing pull request before merge.",
    "ux-architect": "Use before building any user-facing capability.",
}

HEADER = (
    "<!-- Generated by scripts/build-cc-agents.py from ../{slug}.md — "
    "edit the Stella agent, not this file. -->\n"
)


def parse(raw: str) -> tuple[dict[str, str], str]:
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", raw, re.S)
    if not m:
        raise ValueError("no YAML frontmatter")
    data: dict[str, str] = {}
    for line in m.group(1).split("\n"):
        km = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if km:
            data[km.group(1)] = km.group(2).strip()
    return data, m.group(2)


def map_tools(value: str | None) -> str | None:
    """Map a Stella tool list to Claude Code names, preserving order."""
    if value is None or not value.strip():
        return None
    out: list[str] = []
    for item in value.split(","):
        item = item.strip().strip("[]\"'")
        if not item:
            continue
        for mapped in TOOL_MAP.get(item, [item]):
            if mapped not in out:
                out.append(mapped)
    return ", ".join(out) if out else None


def main() -> int:
    if not os.path.isdir(SRC):
        print(f"error: {SRC}/ not found — run from the repository root", file=sys.stderr)
        return 1
    os.makedirs(OUT, exist_ok=True)

    # Remove stale generated files so a renamed agent cannot linger.
    for stale in os.listdir(OUT):
        if stale.endswith(".md"):
            os.remove(os.path.join(OUT, stale))

    written = 0
    for filename in sorted(f for f in os.listdir(SRC) if f.endswith(".md")):
        slug = filename[:-3]
        data, body = parse(open(os.path.join(SRC, filename), encoding="utf-8").read())

        description = data.get("description", "").rstrip(".")
        trigger = TRIGGERS.get(slug)
        if trigger:
            description = f"{description}. {trigger}"

        lines = ["---", f"name: {data.get('name', slug)}", f"description: {description}"]
        tools = map_tools(data.get("tools"))
        if tools:
            lines.append(f"tools: {tools}")
        # `inherit` keeps the agent on whatever model the session is running,
        # so the harness never pins a model id that later goes stale.
        lines.append("model: inherit")
        lines.append("---")

        out_path = os.path.join(OUT, filename)
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
            fh.write(HEADER.format(slug=slug))
            fh.write("\n" + body.lstrip("\n"))
        written += 1

    print(f"wrote {written} Claude Code agents to {OUT}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
